In [1]:
import numpy as np
import pandas as pd

## Load the data

In [2]:
data_preprocessed = pd.read_csv("C:/Users/josep/Downloads/Absenteeism_preprocessed_df.csv")

### Create targets using median  as a cut off

In [3]:
data_preprocessed.head()

reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month value  Date of the week  
0         2     1                          4            7                 1  
1         1     0                          0            7                 1  
2         0     0                          2            7                 2  
3         2     0                          4            7                 3  
4         2     1                          2            7                 3

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(), 1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head()

reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month value  Date of the week  \
0         2     1                          4            7                 1   
1         1     0                          0            7                 1   
2         0     0                          2            7                 2   
3         2     0                          4            7                 3   
4         2     1                          2            7                 3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [8]:
targets.sum()/ targets.shape[0] # data is almost balanced

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis = 1)

In [10]:
data_with_targets.head()

reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-07                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Month value  Date of the week  Excessive Absenteeism  
0         2     1            7                 1                      1  
1         1     0            7                 1                      0  
2         0     0            7                 2                      0  
3         2     0            7                 3                      1  
4         2     1            7                 3                      0

In [11]:
data_with_targets.columns

Index(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Date',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets', 'Month value', 'Date of the week', 'Excessive Absenteeism'],
      dtype='object')

In [12]:
column_names = ['reason_1', 'reason_2', 'reason_3', 'reason_4','Month value', 'Date of the week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pets',  'Excessive Absenteeism']

In [13]:
data_inputs = data_with_targets[column_names]

In [14]:
data_inputs

reason_1  reason_2  reason_3  reason_4  Month value  Date of the week  \
0           0         0         0         1            7                 1   
1           0         0         0         0            7                 1   
2           0         0         0         1            7                 2   
3           1         0         0         0            7                 3   
4           0         0         0         1            7                 3   
..        ...       ...       ...       ...          ...               ...   
695         1         0         0         0            5                 2   
696         1         0         0         0            5                 2   
697         1         0         0         0            5                 3   
698         0         0         0         1            5                 3   
699         0         0         0         1            5                 3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0                 30          0         2     1                      1  
1                 31          0         1     0                      0  
2                 31          0         0     0                      0  
3                 24          0         2     0                      1  
4                 30          0         2     1                      0  
..               ...        ...       ...   ...                    ...  
695               22          1         2     0                      1  
696               24          0         1     2                      0  
697               25          1         0     0                      1  
698               25          1         0     0                      0  
699               25          0         1     1                      0  

[700 rows x 15 columns]

In [15]:
unscaled_inputs = data_inputs.iloc[:,:-1]

## Standardize certain features

In [16]:
#from sklearn.preprocessing import StandardScaler

In [17]:
#absenteeism_scaler = StandardScaler()

In [34]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns, copy=True, with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=False, with_std=with_std)
        self.columns = columns
        self.mean = None
        self.var_ = None
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

    def __repr__(self):
        return f'CustomScaler(columns={self.columns}, copy={self.scaler.copy}, with_std={self.scaler.with_std})'



In [30]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month value',
       'Date of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [31]:
columns_to_scale = ['Month value', 'Date of the week',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Children',
       'Pets']

In [32]:
absenteeism_scaler  = CustomScaler(columns_to_scale)

In [35]:
absenteeism_scaler.fit(unscaled_inputs)

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

In [36]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs) 

In [37]:
scaled_inputs

reason_1  reason_2  reason_3  reason_4  Month value  Date of the week  \
0           0         0         0         1     1.998569          0.675978   
1           0         0         0         0     1.998569          0.675978   
2           0         0         0         1     1.998569          1.351956   
3           1         0         0         0     1.998569          2.027934   
4           0         0         0         1     1.998569          2.027934   
..        ...       ...       ...       ...          ...               ...   
695         1         0         0         0     1.427550          1.351956   
696         1         0         0         0     1.427550          1.351956   
697         1         0         0         0     1.427550          2.027934   
698         0         0         0         1     1.427550          2.027934   
699         0         0         0         1     1.427550          2.027934   

     Transportation Expense  Distance to Work       Age  \
0                  4.361239          2.433441  5.176857   
1                  1.780713          0.878742  7.843722   
2                  2.701252          3.447374  5.961229   
3                  4.210331          0.337978  6.118103   
4                  4.361239          2.433441  5.176857   
..                      ...               ...       ...   
695                2.701252          1.487103  6.274978   
696                3.395428          1.757485  4.392484   
697                4.979961          1.081529  4.392484   
698                3.546336          1.081529  5.019982   
699                4.391420          2.095463  6.274978   

     Daily Work Load Average  Body Mass Index  Education  Children      Pets  
0                   5.989867         7.056066          0  1.799499  0.858176  
1                   5.989867         7.291268          0  0.899750  0.000000  
2                   5.989867         7.291268          0  0.000000  0.000000  
3                   5.989867         5.644853          0  1.799499  0.000000  
4                   5.989867         7.056066          0  1.799499  0.858176  
..                       ...              ...        ...       ...       ...  
695                 5.942409         5.174448          1  1.799499  0.000000  
696                 5.942409         5.644853          0  0.899750  1.716353  
697                 5.942409         5.880055          1  0.000000  0.000000  
698                 5.942409         5.880055          1  0.000000  0.000000  
699                 5.942409         5.880055          0  0.899750  0.858176  

[700 rows x 14 columns]

In [ ]:
scaled_inputs.shape

## SPLIT THE DATA INTO TRAIN AND TEST AND SHUFFLE

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
x_train,x_test,y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [40]:
print(x_train.shape,y_train.shape)

(560, 14) (560,)


In [41]:
print(x_test.shape, y_test.shape)

(140, 14) (140,)


## fitting the model and its accuracy

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [43]:
reg = LogisticRegression()

In [44]:
reg.fit(x_train,y_train)

LogisticRegression()

In [45]:
reg.score(x_train,y_train)

0.775

 ## Manually checking the accuracy

In [46]:
model_outputs = reg.predict(x_train)

In [47]:
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [48]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [49]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [50]:
np.sum(model_outputs == y_train)

434

In [51]:
model_outputs.shape[0]

560

In [52]:
np.sum(model_outputs == y_train)/model_outputs.shape[0]

0.775

## Find the intercepts and coefficients

In [53]:
reg.intercept_

array([-4.80736964])

In [54]:
reg.coef_

array([[ 2.80025082e+00,  9.34289111e-01,  3.09511865e+00,
         8.55936991e-01,  1.66210762e-01, -8.43504078e-02,
         6.12693116e-01, -7.76998513e-03, -1.65898330e-01,
        -1.44787081e-04,  2.71767641e-01, -2.05663704e-01,
         3.61947877e-01, -2.85472238e-01]])

In [55]:
feature_name = unscaled_inputs.columns.values
feature_name

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month value',
       'Date of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [56]:
summary_table = pd.DataFrame(columns = ['Feature Name'],data = feature_name)

In [57]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [58]:
summary_table

Feature Name  Coefficient
0                  reason_1     2.800251
1                  reason_2     0.934289
2                  reason_3     3.095119
3                  reason_4     0.855937
4               Month value     0.166211
5          Date of the week    -0.084350
6    Transportation Expense     0.612693
7          Distance to Work    -0.007770
8                       Age    -0.165898
9   Daily Work Load Average    -0.000145
10          Body Mass Index     0.271768
11                Education    -0.205664
12                 Children     0.361948
13                     Pets    -0.285472

In [59]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficient
0                 Intercept    -4.807370
1                  reason_1     2.800251
2                  reason_2     0.934289
3                  reason_3     3.095119
4                  reason_4     0.855937
5               Month value     0.166211
6          Date of the week    -0.084350
7    Transportation Expense     0.612693
8          Distance to Work    -0.007770
9                       Age    -0.165898
10  Daily Work Load Average    -0.000145
11          Body Mass Index     0.271768
12                Education    -0.205664
13                 Children     0.361948
14                     Pets    -0.285472

In [60]:
summary_table['Odds ratio'] = np.exp(summary_table.Coefficient)

In [61]:
summary_table

Feature Name  Coefficient  Odds ratio
0                 Intercept    -4.807370    0.008169
1                  reason_1     2.800251   16.448772
2                  reason_2     0.934289    2.545403
3                  reason_3     3.095119   22.089859
4                  reason_4     0.855937    2.353579
5               Month value     0.166211    1.180822
6          Date of the week    -0.084350    0.919109
7    Transportation Expense     0.612693    1.845395
8          Distance to Work    -0.007770    0.992260
9                       Age    -0.165898    0.847132
10  Daily Work Load Average    -0.000145    0.999855
11          Body Mass Index     0.271768    1.312282
12                Education    -0.205664    0.814107
13                 Children     0.361948    1.436124
14                     Pets    -0.285472    0.751659

In [62]:
summary_table.sort_values('Odds ratio', ascending = False)

Feature Name  Coefficient  Odds ratio
3                  reason_3     3.095119   22.089859
1                  reason_1     2.800251   16.448772
2                  reason_2     0.934289    2.545403
4                  reason_4     0.855937    2.353579
7    Transportation Expense     0.612693    1.845395
13                 Children     0.361948    1.436124
11          Body Mass Index     0.271768    1.312282
5               Month value     0.166211    1.180822
10  Daily Work Load Average    -0.000145    0.999855
8          Distance to Work    -0.007770    0.992260
6          Date of the week    -0.084350    0.919109
9                       Age    -0.165898    0.847132
12                Education    -0.205664    0.814107
14                     Pets    -0.285472    0.751659
0                 Intercept    -4.807370    0.008169